# docker-compose.yaml
version: '3.9'
services:
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    ports:
      - "5000:5000"
    volumes:
      # ${PWD} будет /workspaces/mlops-zoomcamp/03-orchestration
      # Папка mlflow_data создастся здесь же
      - "${PWD}/mlflow_data:/home/mlflow_data/"
